# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5436:5436
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "db" ]
      interval: 5s
      timeout: 10s
      retries: 5
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: balaputradewa/elysiajs:latest
    ports:
      - 3000:3000
    environment:
      POSTGRES_ADDR: ${POSTGRES_ADDR}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_started
    restart: always
    links:
      - postgres

volumes:
  pgdata: {}
