# fly.toml app configuration file generated for balaputradewa-api on 2024-01-07T21:25:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "balaputradewa-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[env]
 DB_URL=mysql://db-bpd:SwsdKPsaDB4cZj6W@103.56.148.155:3306/db-bpd